# Generated by Django 5.2.3 on 2025-06-11 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('precio_producto', models.IntegerField()),
                ('marca_producto', models.CharField(max_length=20)),
                ('stock_producto', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
